DROP TABLE IF EXISTS ftp_acronyms;
CREATE TABLE ftp_acronyms (
  acronym VARCHAR(255) DEFAULT NULL,
  stands_for VARCHAR(255) DEFAULT NULL,
  effect_dt VARCHAR(255) DEFAULT NULL,
  a_desc VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_address;
CREATE TABLE ftp_address (
  adrid VARCHAR(255) DEFAULT NULL,
  city VARCHAR(255) DEFAULT NULL,
  st VARCHAR(255) DEFAULT NULL,
  zip4 VARCHAR(255) DEFAULT NULL,
  phon VARCHAR(255) DEFAULT NULL,
  fax VARCHAR(255) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_ballot_measures;
CREATE TABLE ftp_ballot_measures (
  election_date VARCHAR(255) DEFAULT NULL,
  filer_id VARCHAR(255) DEFAULT NULL,
  measure_no VARCHAR(255) DEFAULT NULL,
  measure_name VARCHAR(255) DEFAULT NULL,
  measure_short_name VARCHAR(255) DEFAULT NULL,
  jurisdiction VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_cvr2_campaign_disclosure;
CREATE TABLE ftp_cvr2_campaign_disclosure (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  line_item VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  tran_id VARCHAR(255) DEFAULT NULL,
  entity_cd VARCHAR(255) DEFAULT NULL,
  title VARCHAR(255) DEFAULT NULL,
  mail_city VARCHAR(255) DEFAULT NULL,
  mail_st VARCHAR(255) DEFAULT NULL,
  mail_zip4 VARCHAR(255) DEFAULT NULL,
  f460_part VARCHAR(255) DEFAULT NULL,
  cmte_id VARCHAR(255) DEFAULT NULL,
  enty_naml VARCHAR(255) DEFAULT NULL,
  enty_namf VARCHAR(255) DEFAULT NULL,
  enty_namt VARCHAR(255) DEFAULT NULL,
  enty_nams VARCHAR(255) DEFAULT NULL,
  enty_city VARCHAR(255) DEFAULT NULL,
  enty_st VARCHAR(255) DEFAULT NULL,
  enty_zip4 VARCHAR(255) DEFAULT NULL,
  enty_phon VARCHAR(255) DEFAULT NULL,
  enty_fax VARCHAR(255) DEFAULT NULL,
  enty_email VARCHAR(255) DEFAULT NULL,
  tres_naml VARCHAR(255) DEFAULT NULL,
  tres_namf VARCHAR(255) DEFAULT NULL,
  tres_namt VARCHAR(255) DEFAULT NULL,
  tres_nams VARCHAR(255) DEFAULT NULL,
  control_yn VARCHAR(255) DEFAULT NULL,
  office_cd VARCHAR(255) DEFAULT NULL,
  offic_dscr VARCHAR(255) DEFAULT NULL,
  juris_cd VARCHAR(255) DEFAULT NULL,
  juris_dscr VARCHAR(255) DEFAULT NULL,
  dist_no VARCHAR(255) DEFAULT NULL,
  off_s_h_cd VARCHAR(255) DEFAULT NULL,
  bal_name VARCHAR(255) DEFAULT NULL,
  bal_num VARCHAR(255) DEFAULT NULL,
  bal_juris VARCHAR(255) DEFAULT NULL,
  sup_opp_cd VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_cvr2_lobby_disclosure;
CREATE TABLE ftp_cvr2_lobby_disclosure (
  amend_id VARCHAR(255) DEFAULT NULL,
  entity_cd VARCHAR(255) DEFAULT NULL,
  entity_id VARCHAR(255) DEFAULT NULL,
  enty_namf VARCHAR(255) DEFAULT NULL,
  enty_naml VARCHAR(255) DEFAULT NULL,
  enty_nams VARCHAR(255) DEFAULT NULL,
  enty_namt VARCHAR(255) DEFAULT NULL,
  enty_title VARCHAR(255) DEFAULT NULL,
  filing_id VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  line_item VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  tran_id VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_cvr2_registration;
CREATE TABLE ftp_cvr2_registration (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  line_item VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  tran_id VARCHAR(255) DEFAULT NULL,
  entity_cd VARCHAR(255) DEFAULT NULL,
  entity_id VARCHAR(255) DEFAULT NULL,
  enty_naml VARCHAR(255) DEFAULT NULL,
  enty_namf VARCHAR(255) DEFAULT NULL,
  enty_namt VARCHAR(255) DEFAULT NULL,
  enty_nams VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_cvr2_so;
CREATE TABLE ftp_cvr2_so (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  line_item VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  tran_id VARCHAR(255) DEFAULT NULL,
  entity_cd VARCHAR(255) DEFAULT NULL,
  enty_naml VARCHAR(255) DEFAULT NULL,
  enty_namf VARCHAR(255) DEFAULT NULL,
  enty_namt VARCHAR(255) DEFAULT NULL,
  enty_nams VARCHAR(255) DEFAULT NULL,
  item_cd VARCHAR(255) DEFAULT NULL,
  mail_city VARCHAR(255) DEFAULT NULL,
  mail_st VARCHAR(255) DEFAULT NULL,
  mail_zip4 VARCHAR(255) DEFAULT NULL,
  day_phone VARCHAR(255) DEFAULT NULL,
  fax_phone VARCHAR(255) DEFAULT NULL,
  email_adr VARCHAR(255) DEFAULT NULL,
  cmte_id VARCHAR(255) DEFAULT NULL,
  ind_group VARCHAR(255) DEFAULT NULL,
  office_cd VARCHAR(255) DEFAULT NULL,
  offic_dscr VARCHAR(255) DEFAULT NULL,
  juris_cd VARCHAR(255) DEFAULT NULL,
  juris_dscr VARCHAR(255) DEFAULT NULL,
  dist_no VARCHAR(255) DEFAULT NULL,
  off_s_h_cd VARCHAR(255) DEFAULT NULL,
  non_pty_cb VARCHAR(255) DEFAULT NULL,
  party_name VARCHAR(255) DEFAULT NULL,
  bal_num VARCHAR(255) DEFAULT NULL,
  bal_juris VARCHAR(255) DEFAULT NULL,
  sup_opp_cd VARCHAR(255) DEFAULT NULL,
  year_elect VARCHAR(255) DEFAULT NULL,
  pof_title VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_cvr3_verification_info;
CREATE TABLE ftp_cvr3_verification_info (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  line_item VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  tran_id VARCHAR(255) DEFAULT NULL,
  entity_cd VARCHAR(255) DEFAULT NULL,
  sig_date VARCHAR(255) DEFAULT NULL,
  sig_loc VARCHAR(255) DEFAULT NULL,
  sig_naml VARCHAR(255) DEFAULT NULL,
  sig_namf VARCHAR(255) DEFAULT NULL,
  sig_namt VARCHAR(255) DEFAULT NULL,
  sig_nams VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_cvr_campaign_disclosure;
CREATE TABLE ftp_cvr_campaign_disclosure (
  filing_id VARCHAR(255) NOT NULL DEFAULT '',
  amend_id VARCHAR(255) NOT NULL DEFAULT '',
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  filer_id bigint(20) NOT NULL,
  entity_cd VARCHAR(255) DEFAULT NULL,
  filer_naml VARCHAR(255) DEFAULT NULL,
  filer_namf VARCHAR(255) DEFAULT NULL,
  filer_namt VARCHAR(255) DEFAULT NULL,
  filer_nams VARCHAR(255) DEFAULT NULL,
  report_num VARCHAR(255) DEFAULT NULL,
  rpt_date VARCHAR(255) DEFAULT NULL,
  stmt_type VARCHAR(255) DEFAULT NULL,
  late_rptno VARCHAR(255) DEFAULT NULL,
  from_date VARCHAR(255) DEFAULT NULL,
  thru_date VARCHAR(255) DEFAULT NULL,
  elect_date VARCHAR(255) DEFAULT NULL,
  filer_city VARCHAR(255) DEFAULT NULL,
  filer_st VARCHAR(255) DEFAULT NULL,
  filer_zip4 VARCHAR(255) DEFAULT NULL,
  filer_phon VARCHAR(255) DEFAULT NULL,
  filer_fax VARCHAR(255) DEFAULT NULL,
  file_email VARCHAR(255) DEFAULT NULL,
  mail_city VARCHAR(255) DEFAULT NULL,
  mail_st VARCHAR(255) DEFAULT NULL,
  mail_zip4 VARCHAR(255) DEFAULT NULL,
  tres_naml VARCHAR(255) DEFAULT NULL,
  tres_namf VARCHAR(255) DEFAULT NULL,
  tres_namt VARCHAR(255) DEFAULT NULL,
  tres_nams VARCHAR(255) DEFAULT NULL,
  tres_city VARCHAR(255) DEFAULT NULL,
  tres_st VARCHAR(255) DEFAULT NULL,
  tres_zip4 VARCHAR(255) DEFAULT NULL,
  tres_phon VARCHAR(255) DEFAULT NULL,
  tres_fax VARCHAR(255) DEFAULT NULL,
  tres_email VARCHAR(255) DEFAULT NULL,
  cmtte_type VARCHAR(255) DEFAULT NULL,
  control_yn VARCHAR(255) DEFAULT NULL,
  sponsor_yn VARCHAR(255) DEFAULT NULL,
  primfrm_yn VARCHAR(255) DEFAULT NULL,
  brdbase_yn VARCHAR(255) DEFAULT NULL,
  amendexp_1 VARCHAR(255) DEFAULT NULL,
  amendexp_2 VARCHAR(255) DEFAULT NULL,
  amendexp_3 VARCHAR(255) DEFAULT NULL,
  rpt_att_cb VARCHAR(255) DEFAULT NULL,
  cmtte_id VARCHAR(255) DEFAULT NULL,
  reportname VARCHAR(255) DEFAULT NULL,
  rptfromdt VARCHAR(255) DEFAULT NULL,
  rptthrudt VARCHAR(255) DEFAULT NULL,
  emplbus_cb VARCHAR(255) DEFAULT NULL,
  bus_name VARCHAR(255) DEFAULT NULL,
  bus_city VARCHAR(255) DEFAULT NULL,
  bus_st VARCHAR(255) DEFAULT NULL,
  bus_zip4 VARCHAR(255) DEFAULT NULL,
  bus_inter VARCHAR(255) DEFAULT NULL,
  busact_cb VARCHAR(255) DEFAULT NULL,
  busactvity VARCHAR(255) DEFAULT NULL,
  assoc_cb VARCHAR(255) DEFAULT NULL,
  assoc_int VARCHAR(255) DEFAULT NULL,
  other_cb VARCHAR(255) DEFAULT NULL,
  other_int VARCHAR(255) DEFAULT NULL,
  cand_naml VARCHAR(255) DEFAULT NULL,
  cand_namf VARCHAR(255) DEFAULT NULL,
  cand_namt VARCHAR(255) DEFAULT NULL,
  cand_nams VARCHAR(255) DEFAULT NULL,
  cand_city VARCHAR(255) DEFAULT NULL,
  cand_st VARCHAR(255) DEFAULT NULL,
  cand_zip4 VARCHAR(255) DEFAULT NULL,
  cand_phon VARCHAR(255) DEFAULT NULL,
  cand_fax VARCHAR(255) DEFAULT NULL,
  cand_email VARCHAR(255) DEFAULT NULL,
  bal_name VARCHAR(255) DEFAULT NULL,
  bal_num VARCHAR(255) DEFAULT NULL,
  bal_juris VARCHAR(255) DEFAULT NULL,
  office_cd VARCHAR(255) DEFAULT NULL,
  offic_dscr VARCHAR(255) DEFAULT NULL,
  juris_cd VARCHAR(255) DEFAULT NULL,
  juris_dscr VARCHAR(255) DEFAULT NULL,
  dist_no VARCHAR(255) DEFAULT NULL,
  off_s_h_cd VARCHAR(255) DEFAULT NULL,
  sup_opp_cd VARCHAR(255) DEFAULT NULL,
  employer VARCHAR(255) DEFAULT NULL,
  occupation VARCHAR(255) DEFAULT NULL,
  selfemp_cb VARCHAR(255) DEFAULT NULL,
  bal_id VARCHAR(255) DEFAULT NULL,
  cand_id VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (filing_id(10),amend_id(10)),
  KEY filing_id (filing_id(10)),
  KEY amend_id (amend_id(10)),
  KEY filer_id (filer_id),
  KEY form_type (form_type(10)),
  KEY office_cd (office_cd(10)),
  KEY entity_cd (entity_cd(10))
);

DROP TABLE IF EXISTS ftp_cvr_e530;
CREATE TABLE ftp_cvr_e530 (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  entity_cd VARCHAR(255) DEFAULT NULL,
  filer_naml VARCHAR(255) DEFAULT NULL,
  filer_namf VARCHAR(255) DEFAULT NULL,
  filer_namt VARCHAR(255) DEFAULT NULL,
  filer_nams VARCHAR(255) DEFAULT NULL,
  report_num VARCHAR(255) DEFAULT NULL,
  rpt_date VARCHAR(255) DEFAULT NULL,
  filer_city VARCHAR(255) DEFAULT NULL,
  filer_st VARCHAR(255) DEFAULT NULL,
  filer_zip4 VARCHAR(255) DEFAULT NULL,
  occupation VARCHAR(400) DEFAULT NULL,
  employer VARCHAR(400) DEFAULT NULL,
  cand_naml VARCHAR(255) DEFAULT NULL,
  cand_namf VARCHAR(255) DEFAULT NULL,
  cand_namt VARCHAR(255) DEFAULT NULL,
  cand_nams VARCHAR(255) DEFAULT NULL,
  district_cd VARCHAR(255) DEFAULT NULL,
  office_cd VARCHAR(255) DEFAULT NULL,
  pmnt_dt VARCHAR(255) DEFAULT NULL,
  pmnt_amount VARCHAR(255) DEFAULT NULL,
  type_literature VARCHAR(255) DEFAULT NULL,
  type_printads VARCHAR(255) DEFAULT NULL,
  type_radio VARCHAR(255) DEFAULT NULL,
  type_tv VARCHAR(255) DEFAULT NULL,
  type_it VARCHAR(255) DEFAULT NULL,
  type_billboards VARCHAR(255) DEFAULT NULL,
  type_other VARCHAR(255) DEFAULT NULL,
  other_desc VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_cvr_lobby_disclosure;
CREATE TABLE ftp_cvr_lobby_disclosure (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  sender_id VARCHAR(255) DEFAULT NULL,
  filer_id VARCHAR(255) DEFAULT NULL,
  entity_cd VARCHAR(255) DEFAULT NULL,
  filer_naml VARCHAR(255) DEFAULT NULL,
  filer_namf VARCHAR(255) DEFAULT NULL,
  filer_namt VARCHAR(255) DEFAULT NULL,
  filer_nams VARCHAR(255) DEFAULT NULL,
  report_num VARCHAR(255) DEFAULT NULL,
  rpt_date VARCHAR(255) DEFAULT NULL,
  from_date VARCHAR(255) DEFAULT NULL,
  thru_date VARCHAR(255) DEFAULT NULL,
  cum_beg_dt VARCHAR(255) DEFAULT NULL,
  firm_id VARCHAR(255) DEFAULT NULL,
  firm_name VARCHAR(255) DEFAULT NULL,
  firm_city VARCHAR(255) DEFAULT NULL,
  firm_st VARCHAR(255) DEFAULT NULL,
  firm_zip4 VARCHAR(255) DEFAULT NULL,
  firm_phon VARCHAR(255) DEFAULT NULL,
  mail_city VARCHAR(255) DEFAULT NULL,
  mail_st VARCHAR(255) DEFAULT NULL,
  mail_zip4 VARCHAR(255) DEFAULT NULL,
  mail_phon VARCHAR(255) DEFAULT NULL,
  sig_date VARCHAR(255) DEFAULT NULL,
  sig_loc VARCHAR(255) DEFAULT NULL,
  sig_naml VARCHAR(255) DEFAULT NULL,
  sig_namf VARCHAR(255) DEFAULT NULL,
  sig_namt VARCHAR(255) DEFAULT NULL,
  sig_nams VARCHAR(255) DEFAULT NULL,
  prn_naml VARCHAR(255) DEFAULT NULL,
  prn_namf VARCHAR(255) DEFAULT NULL,
  prn_namt VARCHAR(255) DEFAULT NULL,
  prn_nams VARCHAR(255) DEFAULT NULL,
  sig_title VARCHAR(255) DEFAULT NULL,
  nopart1_cb VARCHAR(255) DEFAULT NULL,
  nopart2_cb VARCHAR(255) DEFAULT NULL,
  part1_1_cb VARCHAR(255) DEFAULT NULL,
  part1_2_cb VARCHAR(255) DEFAULT NULL,
  ctrib_n_cb VARCHAR(255) DEFAULT NULL,
  ctrib_y_cb VARCHAR(255) DEFAULT NULL,
  lby_actvty VARCHAR(255) DEFAULT NULL,
  lobby_n_cb VARCHAR(255) DEFAULT NULL,
  lobby_y_cb VARCHAR(255) DEFAULT NULL,
  major_naml VARCHAR(255) DEFAULT NULL,
  major_namf VARCHAR(255) DEFAULT NULL,
  major_namt VARCHAR(255) DEFAULT NULL,
  major_nams VARCHAR(255) DEFAULT NULL,
  rcpcmte_nm VARCHAR(255) DEFAULT NULL,
  rcpcmte_id VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_cvr_registration;
CREATE TABLE ftp_cvr_registration (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  sender_id VARCHAR(255) DEFAULT NULL,
  filer_id VARCHAR(255) DEFAULT NULL,
  entity_cd VARCHAR(255) DEFAULT NULL,
  filer_naml VARCHAR(255) DEFAULT NULL,
  filer_namf VARCHAR(255) DEFAULT NULL,
  filer_namt VARCHAR(255) DEFAULT NULL,
  filer_nams VARCHAR(255) DEFAULT NULL,
  report_num VARCHAR(255) DEFAULT NULL,
  rpt_date VARCHAR(255) DEFAULT NULL,
  ls_beg_yr VARCHAR(255) DEFAULT NULL,
  ls_end_yr VARCHAR(255) DEFAULT NULL,
  qual_date VARCHAR(255) DEFAULT NULL,
  eff_date VARCHAR(255) DEFAULT NULL,
  bus_city VARCHAR(255) DEFAULT NULL,
  bus_st VARCHAR(255) DEFAULT NULL,
  bus_zip4 VARCHAR(255) DEFAULT NULL,
  bus_phon VARCHAR(255) DEFAULT NULL,
  bus_fax VARCHAR(255) DEFAULT NULL,
  bus_email VARCHAR(255) DEFAULT NULL,
  mail_city VARCHAR(255) DEFAULT NULL,
  mail_st VARCHAR(255) DEFAULT NULL,
  mail_zip4 VARCHAR(255) DEFAULT NULL,
  mail_phon VARCHAR(255) DEFAULT NULL,
  sig_date VARCHAR(255) DEFAULT NULL,
  sig_loc VARCHAR(255) DEFAULT NULL,
  sig_naml VARCHAR(255) DEFAULT NULL,
  sig_namf VARCHAR(255) DEFAULT NULL,
  sig_namt VARCHAR(255) DEFAULT NULL,
  sig_nams VARCHAR(255) DEFAULT NULL,
  prn_naml VARCHAR(255) DEFAULT NULL,
  prn_namf VARCHAR(255) DEFAULT NULL,
  prn_namt VARCHAR(255) DEFAULT NULL,
  prn_nams VARCHAR(255) DEFAULT NULL,
  sig_title VARCHAR(255) DEFAULT NULL,
  stmt_firm VARCHAR(255) DEFAULT NULL,
  ind_cb VARCHAR(255) DEFAULT NULL,
  bus_cb VARCHAR(255) DEFAULT NULL,
  trade_cb VARCHAR(255) DEFAULT NULL,
  oth_cb VARCHAR(255) DEFAULT NULL,
  a_b_name VARCHAR(255) DEFAULT NULL,
  a_b_city VARCHAR(255) DEFAULT NULL,
  a_b_st VARCHAR(255) DEFAULT NULL,
  a_b_zip4 VARCHAR(255) DEFAULT NULL,
  descrip_1 VARCHAR(255) DEFAULT NULL,
  descrip_2 VARCHAR(255) DEFAULT NULL,
  c_less50 VARCHAR(255) DEFAULT NULL,
  c_more50 VARCHAR(255) DEFAULT NULL,
  ind_class VARCHAR(255) DEFAULT NULL,
  ind_descr VARCHAR(255) DEFAULT NULL,
  bus_class VARCHAR(255) DEFAULT NULL,
  bus_descr VARCHAR(255) DEFAULT NULL,
  auth_name VARCHAR(255) DEFAULT NULL,
  auth_city VARCHAR(255) DEFAULT NULL,
  auth_st VARCHAR(255) DEFAULT NULL,
  auth_zip4 VARCHAR(255) DEFAULT NULL,
  lobby_int VARCHAR(255) DEFAULT NULL,
  influen_yn VARCHAR(255) DEFAULT NULL,
  firm_name VARCHAR(255) DEFAULT NULL,
  newcert_cb VARCHAR(255) DEFAULT NULL,
  rencert_cb VARCHAR(255) DEFAULT NULL,
  complet_dt VARCHAR(255) DEFAULT NULL,
  lby_reg_cb VARCHAR(255) DEFAULT NULL,
  lby_604_cb VARCHAR(255) DEFAULT NULL,
  st_leg_yn VARCHAR(255) DEFAULT NULL,
  st_agency VARCHAR(255) DEFAULT NULL,
  lobby_cb VARCHAR(255) DEFAULT NULL,
  l_firm_cb VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_cvr_so;
CREATE TABLE ftp_cvr_so (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  filer_id VARCHAR(255) DEFAULT NULL,
  entity_cd VARCHAR(255) DEFAULT NULL,
  filer_naml VARCHAR(255) DEFAULT NULL,
  filer_namf VARCHAR(255) DEFAULT NULL,
  filer_namt VARCHAR(255) DEFAULT NULL,
  filer_nams VARCHAR(255) DEFAULT NULL,
  report_num VARCHAR(255) DEFAULT NULL,
  rpt_date VARCHAR(255) DEFAULT NULL,
  qual_cb VARCHAR(255) DEFAULT NULL,
  qualfy_dt VARCHAR(255) DEFAULT NULL,
  term_date VARCHAR(255) DEFAULT NULL,
  city VARCHAR(255) DEFAULT NULL,
  st VARCHAR(255) DEFAULT NULL,
  zip4 VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(255) DEFAULT NULL,
  county_res VARCHAR(255) DEFAULT NULL,
  county_act VARCHAR(255) DEFAULT NULL,
  mail_city VARCHAR(255) DEFAULT NULL,
  mail_st VARCHAR(255) DEFAULT NULL,
  mail_zip4 VARCHAR(255) DEFAULT NULL,
  cmte_fax VARCHAR(255) DEFAULT NULL,
  cmte_email VARCHAR(255) DEFAULT NULL,
  tres_naml VARCHAR(255) DEFAULT NULL,
  tres_namf VARCHAR(255) DEFAULT NULL,
  tres_namt VARCHAR(255) DEFAULT NULL,
  tres_nams VARCHAR(255) DEFAULT NULL,
  tres_city VARCHAR(255) DEFAULT NULL,
  tres_st VARCHAR(255) DEFAULT NULL,
  tres_zip4 VARCHAR(255) DEFAULT NULL,
  tres_phon VARCHAR(255) DEFAULT NULL,
  actvty_lvl VARCHAR(255) DEFAULT NULL,
  com82013yn VARCHAR(255) DEFAULT NULL,
  com82013nm VARCHAR(255) DEFAULT NULL,
  com82013id VARCHAR(255) DEFAULT NULL,
  control_cb VARCHAR(255) DEFAULT NULL,
  bank_nam VARCHAR(255) DEFAULT NULL,
  bank_adr1 VARCHAR(255) DEFAULT NULL,
  bank_adr2 VARCHAR(255) DEFAULT NULL,
  bank_city VARCHAR(255) DEFAULT NULL,
  bank_st VARCHAR(255) DEFAULT NULL,
  bank_zip4 VARCHAR(255) DEFAULT NULL,
  bank_phon VARCHAR(255) DEFAULT NULL,
  acct_opendt VARCHAR(255) DEFAULT NULL,
  surplusdsp VARCHAR(255) DEFAULT NULL,
  primfc_cb VARCHAR(255) DEFAULT NULL,
  genpurp_cb VARCHAR(255) DEFAULT NULL,
  gpc_descr VARCHAR(255) DEFAULT NULL,
  sponsor_cb VARCHAR(255) DEFAULT NULL,
  brdbase_cb VARCHAR(255) DEFAULT NULL,
  smcont_qualdt VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_debt;
CREATE TABLE ftp_debt (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  line_item VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  tran_id VARCHAR(255) DEFAULT NULL,
  entity_cd VARCHAR(255) DEFAULT NULL,
  payee_naml VARCHAR(255) DEFAULT NULL,
  payee_namf VARCHAR(255) DEFAULT NULL,
  payee_namt VARCHAR(255) DEFAULT NULL,
  payee_nams VARCHAR(255) DEFAULT NULL,
  payee_city VARCHAR(255) DEFAULT NULL,
  payee_st VARCHAR(255) DEFAULT NULL,
  payee_zip4 VARCHAR(255) DEFAULT NULL,
  beg_bal VARCHAR(255) DEFAULT NULL,
  amt_incur VARCHAR(255) DEFAULT NULL,
  amt_paid VARCHAR(255) DEFAULT NULL,
  end_bal VARCHAR(255) DEFAULT NULL,
  expn_code VARCHAR(255) DEFAULT NULL,
  expn_dscr VARCHAR(255) DEFAULT NULL,
  cmte_id VARCHAR(255) DEFAULT NULL,
  tres_naml VARCHAR(255) DEFAULT NULL,
  tres_namf VARCHAR(255) DEFAULT NULL,
  tres_namt VARCHAR(255) DEFAULT NULL,
  tres_nams VARCHAR(255) DEFAULT NULL,
  tres_city VARCHAR(255) DEFAULT NULL,
  tres_st VARCHAR(255) DEFAULT NULL,
  tres_zip4 VARCHAR(255) DEFAULT NULL,
  memo_code VARCHAR(255) DEFAULT NULL,
  memo_refno VARCHAR(255) DEFAULT NULL,
  bakref_tid VARCHAR(255) DEFAULT NULL,
  xref_schnm VARCHAR(255) DEFAULT NULL,
  xref_match VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_efs_filing_log;
CREATE TABLE ftp_efs_filing_log (
  filing_date VARCHAR(255) DEFAULT NULL,
  filingstatus VARCHAR(255) DEFAULT NULL,
  vendor VARCHAR(255) DEFAULT NULL,
  filer_id VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  error_no VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_expn;
CREATE TABLE ftp_expn (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  line_item VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  tran_id VARCHAR(255) DEFAULT NULL,
  entity_cd VARCHAR(255) DEFAULT NULL,
  payee_naml VARCHAR(255) DEFAULT NULL,
  payee_namf VARCHAR(255) DEFAULT NULL,
  payee_namt VARCHAR(255) DEFAULT NULL,
  payee_nams VARCHAR(255) DEFAULT NULL,
  payee_city VARCHAR(255) DEFAULT NULL,
  payee_st VARCHAR(255) DEFAULT NULL,
  payee_zip4 VARCHAR(255) DEFAULT NULL,
  expn_date VARCHAR(255) DEFAULT NULL,
  amount VARCHAR(255) DEFAULT NULL,
  cum_ytd VARCHAR(255) DEFAULT NULL,
  cum_oth VARCHAR(255) DEFAULT NULL,
  expn_chkno VARCHAR(255) DEFAULT NULL,
  expn_code VARCHAR(255) DEFAULT NULL,
  expn_dscr VARCHAR(255) DEFAULT NULL,
  agent_naml VARCHAR(255) DEFAULT NULL,
  agent_namf VARCHAR(255) DEFAULT NULL,
  agent_namt VARCHAR(255) DEFAULT NULL,
  agent_nams VARCHAR(255) DEFAULT NULL,
  cmte_id VARCHAR(255) DEFAULT NULL,
  tres_naml VARCHAR(255) DEFAULT NULL,
  tres_namf VARCHAR(255) DEFAULT NULL,
  tres_namt VARCHAR(255) DEFAULT NULL,
  tres_nams VARCHAR(255) DEFAULT NULL,
  tres_city VARCHAR(255) DEFAULT NULL,
  tres_st VARCHAR(255) DEFAULT NULL,
  tres_zip4 VARCHAR(255) DEFAULT NULL,
  cand_naml VARCHAR(255) DEFAULT NULL,
  cand_namf VARCHAR(255) DEFAULT NULL,
  cand_namt VARCHAR(255) DEFAULT NULL,
  cand_nams VARCHAR(255) DEFAULT NULL,
  office_cd VARCHAR(255) DEFAULT NULL,
  offic_dscr VARCHAR(255) DEFAULT NULL,
  juris_cd VARCHAR(255) DEFAULT NULL,
  juris_dscr VARCHAR(255) DEFAULT NULL,
  dist_no VARCHAR(255) DEFAULT NULL,
  off_s_h_cd VARCHAR(255) DEFAULT NULL,
  bal_name VARCHAR(255) DEFAULT NULL,
  bal_num VARCHAR(255) DEFAULT NULL,
  bal_juris VARCHAR(255) DEFAULT NULL,
  sup_opp_cd VARCHAR(255) DEFAULT NULL,
  memo_code VARCHAR(255) DEFAULT NULL,
  memo_refno VARCHAR(255) DEFAULT NULL,
  bakref_tid VARCHAR(255) DEFAULT NULL,
  g_from_e_f VARCHAR(255) DEFAULT NULL,
  xref_schnm VARCHAR(255) DEFAULT NULL,
  xref_match VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_f495p2;
CREATE TABLE ftp_f495p2 (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  line_item VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  elect_date VARCHAR(255) DEFAULT NULL,
  electjuris VARCHAR(255) DEFAULT NULL,
  contribamt VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_f501_502;
CREATE TABLE ftp_f501_502 (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  filer_id VARCHAR(255) DEFAULT NULL,
  committee_id VARCHAR(255) DEFAULT NULL,
  entity_cd VARCHAR(255) DEFAULT NULL,
  report_num VARCHAR(255) DEFAULT NULL,
  rpt_date VARCHAR(255) DEFAULT NULL,
  stmt_type VARCHAR(255) DEFAULT NULL,
  from_date VARCHAR(255) DEFAULT NULL,
  thru_date VARCHAR(255) DEFAULT NULL,
  elect_date VARCHAR(255) DEFAULT NULL,
  cand_naml VARCHAR(255) DEFAULT NULL,
  cand_namf VARCHAR(255) DEFAULT NULL,
  can_namm VARCHAR(255) DEFAULT NULL,
  cand_namt VARCHAR(255) DEFAULT NULL,
  cand_nams VARCHAR(255) DEFAULT NULL,
  moniker_pos VARCHAR(255) DEFAULT NULL,
  moniker VARCHAR(255) DEFAULT NULL,
  cand_city VARCHAR(255) DEFAULT NULL,
  cand_st VARCHAR(255) DEFAULT NULL,
  cand_zip4 VARCHAR(255) DEFAULT NULL,
  cand_phon VARCHAR(255) DEFAULT NULL,
  cand_fax VARCHAR(255) DEFAULT NULL,
  cand_email VARCHAR(255) DEFAULT NULL,
  fin_naml VARCHAR(255) DEFAULT NULL,
  fin_namf VARCHAR(255) DEFAULT NULL,
  fin_namt VARCHAR(255) DEFAULT NULL,
  fin_nams VARCHAR(255) DEFAULT NULL,
  fin_city VARCHAR(255) DEFAULT NULL,
  fin_st VARCHAR(255) DEFAULT NULL,
  fin_zip4 VARCHAR(255) DEFAULT NULL,
  fin_phon VARCHAR(255) DEFAULT NULL,
  fin_fax VARCHAR(255) DEFAULT NULL,
  fin_email VARCHAR(255) DEFAULT NULL,
  office_cd VARCHAR(255) DEFAULT NULL,
  offic_dscr VARCHAR(255) DEFAULT NULL,
  agency_nam VARCHAR(255) DEFAULT NULL,
  juris_cd VARCHAR(255) DEFAULT NULL,
  juris_dscr VARCHAR(255) DEFAULT NULL,
  dist_no VARCHAR(255) DEFAULT NULL,
  party VARCHAR(255) DEFAULT NULL,
  yr_of_elec VARCHAR(255) DEFAULT NULL,
  elec_type VARCHAR(255) DEFAULT NULL,
  execute_dt VARCHAR(255) DEFAULT NULL,
  can_sig VARCHAR(255) DEFAULT NULL,
  account_no VARCHAR(255) DEFAULT NULL,
  acct_op_dt VARCHAR(255) DEFAULT NULL,
  party_cd VARCHAR(255) DEFAULT NULL,
  district_cd VARCHAR(255) DEFAULT NULL,
  accept_limit_yn VARCHAR(255) DEFAULT NULL,
  did_exceed_dt VARCHAR(255) DEFAULT NULL,
  cntrb_prsnl_fnds_dt VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_f690p2;
CREATE TABLE ftp_f690p2 (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  line_item VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  exec_date VARCHAR(255) DEFAULT NULL,
  from_date VARCHAR(255) DEFAULT NULL,
  thru_date VARCHAR(255) DEFAULT NULL,
  chg_parts VARCHAR(255) DEFAULT NULL,
  chg_sects VARCHAR(255) DEFAULT NULL,
  amend_txt1 VARCHAR(330) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_filer_acronyms;
CREATE TABLE ftp_filer_acronyms (
  acronym VARCHAR(255) DEFAULT NULL,
  filer_id VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_filer_address;
CREATE TABLE ftp_filer_address (
  filer_id VARCHAR(255) DEFAULT NULL,
  adrid VARCHAR(255) DEFAULT NULL,
  effect_dt VARCHAR(255) DEFAULT NULL,
  add_type VARCHAR(255) DEFAULT NULL,
  session_id VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_filer_ethics_class;
CREATE TABLE ftp_filer_ethics_class (
  filer_id VARCHAR(255) DEFAULT NULL,
  session_id VARCHAR(255) DEFAULT NULL,
  ethics_date VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_filer_filings;
CREATE TABLE ftp_filer_filings (
  filer_id bigint(20) NOT NULL,
  filing_id VARCHAR(255) NOT NULL DEFAULT '',
  period_id VARCHAR(255) DEFAULT NULL,
  form_id VARCHAR(255) NOT NULL DEFAULT '',
  filing_sequence VARCHAR(255) NOT NULL DEFAULT '',
  filing_date VARCHAR(255) DEFAULT NULL,
  stmnt_type VARCHAR(255) DEFAULT NULL,
  stmnt_status VARCHAR(255) DEFAULT NULL,
  session_id smallint(6) NOT NULL,
  user_id VARCHAR(255) DEFAULT NULL,
  special_audit VARCHAR(255) DEFAULT NULL,
  fine_audit VARCHAR(255) DEFAULT NULL,
  rpt_start VARCHAR(255) DEFAULT NULL,
  rpt_end VARCHAR(255) DEFAULT NULL,
  rpt_date VARCHAR(255) DEFAULT NULL,
  filing_type VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (filer_id,filing_id(10),form_id(10),filing_sequence(10)),
  KEY filer_id (filer_id),
  KEY filing_id (filing_id(10)),
  KEY filing_sequence (filing_sequence(10)),
  KEY form_id (form_id(10)),
  KEY rpt_end (rpt_end(10)),
  KEY session_id (session_id),
  KEY multi_01 (filer_id,session_id)
);

DROP TABLE IF EXISTS ftp_filer_interests;
CREATE TABLE ftp_filer_interests (
  filer_id VARCHAR(255) DEFAULT NULL,
  session_id VARCHAR(255) DEFAULT NULL,
  interest_cd VARCHAR(255) DEFAULT NULL,
  effect_date VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_filer_links;
CREATE TABLE ftp_filer_links (
  filer_id_a VARCHAR(255) DEFAULT NULL,
  filer_id_b VARCHAR(255) DEFAULT NULL,
  active_flg VARCHAR(255) DEFAULT NULL,
  session_id VARCHAR(255) DEFAULT NULL,
  link_type VARCHAR(255) DEFAULT NULL,
  link_desc VARCHAR(255) DEFAULT NULL,
  effect_dt VARCHAR(255) DEFAULT NULL,
  dominate_filer VARCHAR(255) DEFAULT NULL,
  termination_dt VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_filer_status_types;
CREATE TABLE ftp_filer_status_types (
  status_type VARCHAR(255) DEFAULT NULL,
  status_desc VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_filer_to_filer_type;
CREATE TABLE ftp_filer_to_filer_type (
  filer_id VARCHAR(255) DEFAULT NULL,
  filer_type VARCHAR(255) DEFAULT NULL,
  active VARCHAR(255) DEFAULT NULL,
  race VARCHAR(255) DEFAULT NULL,
  session_id VARCHAR(255) DEFAULT NULL,
  category VARCHAR(255) DEFAULT NULL,
  category_type VARCHAR(255) DEFAULT NULL,
  sub_category VARCHAR(255) DEFAULT NULL,
  effect_dt VARCHAR(255) DEFAULT NULL,
  sub_category_type VARCHAR(255) DEFAULT NULL,
  election_type VARCHAR(255) DEFAULT NULL,
  sub_category_a VARCHAR(255) DEFAULT NULL,
  nyq_dt VARCHAR(255) DEFAULT NULL,
  party_cd VARCHAR(255) DEFAULT NULL,
  county_cd VARCHAR(255) DEFAULT NULL,
  district_cd VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_filer_types;
CREATE TABLE ftp_filer_types (
  filer_type VARCHAR(255) DEFAULT NULL,
  description VARCHAR(255) DEFAULT NULL,
  grp_type VARCHAR(255) DEFAULT NULL,
  calc_use VARCHAR(255) DEFAULT NULL,
  grace_period VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_filer_xref;
CREATE TABLE ftp_filer_xref (
  filer_id bigint(20) DEFAULT NULL,
  xref_id bigint(20) DEFAULT NULL,
  effect_dt VARCHAR(255) DEFAULT NULL,
  migration_source VARCHAR(255) DEFAULT NULL,
  KEY xref_id (xref_id),
  KEY filer_id (filer_id)
);

DROP TABLE IF EXISTS ftp_filername;
CREATE TABLE ftp_filername (
  xref_filer_id VARCHAR(255) DEFAULT NULL,
  filer_id VARCHAR(255) DEFAULT NULL,
  filer_type VARCHAR(255) DEFAULT NULL,
  status VARCHAR(255) DEFAULT NULL,
  effect_dt VARCHAR(255) DEFAULT NULL,
  naml VARCHAR(255) DEFAULT NULL,
  namf VARCHAR(255) DEFAULT NULL,
  namt VARCHAR(255) DEFAULT NULL,
  nams VARCHAR(255) DEFAULT NULL,
  adr1 VARCHAR(255) DEFAULT NULL,
  adr2 VARCHAR(255) DEFAULT NULL,
  city VARCHAR(255) DEFAULT NULL,
  st VARCHAR(255) DEFAULT NULL,
  zip4 VARCHAR(255) DEFAULT NULL,
  phon VARCHAR(255) DEFAULT NULL,
  fax VARCHAR(255) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_filers;
CREATE TABLE ftp_filers (
  filer_id VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_filing_period;
CREATE TABLE ftp_filing_period (
  period_id VARCHAR(255) DEFAULT NULL,
  start_date VARCHAR(255) DEFAULT NULL,
  end_date VARCHAR(255) DEFAULT NULL,
  period_type VARCHAR(255) DEFAULT NULL,
  per_grp_type VARCHAR(255) DEFAULT NULL,
  period_desc VARCHAR(255) DEFAULT NULL,
  deadline VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_filings;
CREATE TABLE ftp_filings (
  filing_id VARCHAR(255) DEFAULT NULL,
  filing_type VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_group_types;
CREATE TABLE ftp_group_types (
  grp_id VARCHAR(255) DEFAULT NULL,
  grp_name VARCHAR(255) DEFAULT NULL,
  grp_desc VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_hdr;
CREATE TABLE ftp_hdr (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  ef_type VARCHAR(255) DEFAULT NULL,
  state_cd VARCHAR(255) DEFAULT NULL,
  cal_ver VARCHAR(255) DEFAULT NULL,
  soft_name VARCHAR(255) DEFAULT NULL,
  soft_ver VARCHAR(255) DEFAULT NULL,
  hdrcomment VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_header;
CREATE TABLE ftp_header (
  line_number VARCHAR(255) DEFAULT NULL,
  form_id VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  section_label VARCHAR(255) DEFAULT NULL,
  comments1 VARCHAR(255) DEFAULT NULL,
  comments2 VARCHAR(255) DEFAULT NULL,
  label VARCHAR(255) DEFAULT NULL,
  column_a VARCHAR(255) DEFAULT NULL,
  column_b VARCHAR(255) DEFAULT NULL,
  column_c VARCHAR(255) DEFAULT NULL,
  show_c VARCHAR(255) DEFAULT NULL,
  show_b VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_image_links;
CREATE TABLE ftp_image_links (
  img_link_id VARCHAR(255) DEFAULT NULL,
  img_link_type VARCHAR(255) DEFAULT NULL,
  img_id VARCHAR(255) DEFAULT NULL,
  img_type VARCHAR(255) DEFAULT NULL,
  img_dt VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_latt;
CREATE TABLE ftp_latt (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  line_item VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  tran_id VARCHAR(255) DEFAULT NULL,
  entity_cd VARCHAR(255) DEFAULT NULL,
  recip_naml VARCHAR(255) DEFAULT NULL,
  recip_namf VARCHAR(255) DEFAULT NULL,
  recip_namt VARCHAR(255) DEFAULT NULL,
  recip_nams VARCHAR(255) DEFAULT NULL,
  recip_city VARCHAR(255) DEFAULT NULL,
  recip_st VARCHAR(255) DEFAULT NULL,
  recip_zip4 VARCHAR(255) DEFAULT NULL,
  pmt_date VARCHAR(255) DEFAULT NULL,
  amount VARCHAR(255) DEFAULT NULL,
  cum_amt VARCHAR(255) DEFAULT NULL,
  cumbeg_dt VARCHAR(255) DEFAULT NULL,
  memo_code VARCHAR(255) DEFAULT NULL,
  memo_refno VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_lccm;
CREATE TABLE ftp_lccm (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  line_item VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  tran_id VARCHAR(255) DEFAULT NULL,
  entity_cd VARCHAR(255) DEFAULT NULL,
  recip_naml VARCHAR(255) DEFAULT NULL,
  recip_namf VARCHAR(255) DEFAULT NULL,
  recip_namt VARCHAR(255) DEFAULT NULL,
  recip_nams VARCHAR(255) DEFAULT NULL,
  recip_city VARCHAR(255) DEFAULT NULL,
  recip_st VARCHAR(255) DEFAULT NULL,
  recip_zip4 VARCHAR(255) DEFAULT NULL,
  recip_id VARCHAR(255) DEFAULT NULL,
  ctrib_naml VARCHAR(255) DEFAULT NULL,
  ctrib_namf VARCHAR(255) DEFAULT NULL,
  ctrib_namt VARCHAR(255) DEFAULT NULL,
  ctrib_nams VARCHAR(255) DEFAULT NULL,
  ctrib_date VARCHAR(255) DEFAULT NULL,
  amount VARCHAR(255) DEFAULT NULL,
  memo_code VARCHAR(255) DEFAULT NULL,
  memo_refno VARCHAR(255) DEFAULT NULL,
  bakref_tid VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_legislative_sessions;
CREATE TABLE ftp_legislative_sessions (
  session_id VARCHAR(255) DEFAULT NULL,
  begin_date VARCHAR(255) DEFAULT NULL,
  end_date VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_lemp;
CREATE TABLE ftp_lemp (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  line_item VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  client_id VARCHAR(255) DEFAULT NULL,
  cli_naml VARCHAR(255) DEFAULT NULL,
  cli_namf VARCHAR(255) DEFAULT NULL,
  cli_namt VARCHAR(255) DEFAULT NULL,
  cli_nams VARCHAR(255) DEFAULT NULL,
  cli_city VARCHAR(255) DEFAULT NULL,
  cli_st VARCHAR(255) DEFAULT NULL,
  cli_zip4 VARCHAR(255) DEFAULT NULL,
  cli_phon VARCHAR(255) DEFAULT NULL,
  eff_date VARCHAR(255) DEFAULT NULL,
  con_period VARCHAR(255) DEFAULT NULL,
  agencylist VARCHAR(255) DEFAULT NULL,
  descrip VARCHAR(255) DEFAULT NULL,
  subfirm_id VARCHAR(255) DEFAULT NULL,
  sub_name VARCHAR(255) DEFAULT NULL,
  sub_city VARCHAR(255) DEFAULT NULL,
  sub_st VARCHAR(255) DEFAULT NULL,
  sub_zip4 VARCHAR(255) DEFAULT NULL,
  sub_phon VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_lexp;
CREATE TABLE ftp_lexp (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  line_item VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  tran_id VARCHAR(255) DEFAULT NULL,
  recsubtype VARCHAR(255) DEFAULT NULL,
  entity_cd VARCHAR(255) DEFAULT NULL,
  payee_naml VARCHAR(255) DEFAULT NULL,
  payee_namf VARCHAR(255) DEFAULT NULL,
  payee_namt VARCHAR(255) DEFAULT NULL,
  payee_nams VARCHAR(255) DEFAULT NULL,
  payee_city VARCHAR(255) DEFAULT NULL,
  payee_st VARCHAR(255) DEFAULT NULL,
  payee_zip4 VARCHAR(255) DEFAULT NULL,
  credcardco VARCHAR(255) DEFAULT NULL,
  bene_name VARCHAR(255) DEFAULT NULL,
  bene_posit VARCHAR(255) DEFAULT NULL,
  bene_amt VARCHAR(255) DEFAULT NULL,
  expn_dscr VARCHAR(255) DEFAULT NULL,
  expn_date VARCHAR(255) DEFAULT NULL,
  amount VARCHAR(255) DEFAULT NULL,
  memo_code VARCHAR(255) DEFAULT NULL,
  memo_refno VARCHAR(255) DEFAULT NULL,
  bakref_tid VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_loan;
CREATE TABLE ftp_loan (
  filing_id VARCHAR(255) NOT NULL DEFAULT '',
  amend_id VARCHAR(255) NOT NULL DEFAULT '',
  line_item VARCHAR(255) NOT NULL DEFAULT '',
  rec_type VARCHAR(255) NOT NULL DEFAULT '',
  form_type VARCHAR(255) NOT NULL DEFAULT '',
  tran_id VARCHAR(255) DEFAULT NULL,
  loan_type VARCHAR(255) DEFAULT NULL,
  entity_cd VARCHAR(255) DEFAULT NULL,
  lndr_naml VARCHAR(255) DEFAULT NULL,
  lndr_namf VARCHAR(255) DEFAULT NULL,
  lndr_namt VARCHAR(255) DEFAULT NULL,
  lndr_nams VARCHAR(255) DEFAULT NULL,
  loan_city VARCHAR(255) DEFAULT NULL,
  loan_st VARCHAR(255) DEFAULT NULL,
  loan_zip4 VARCHAR(255) DEFAULT NULL,
  loan_date1 VARCHAR(255) DEFAULT NULL,
  loan_date2 VARCHAR(255) DEFAULT NULL,
  loan_amt1 VARCHAR(255) DEFAULT NULL,
  loan_amt2 VARCHAR(255) DEFAULT NULL,
  loan_amt3 VARCHAR(255) DEFAULT NULL,
  loan_amt4 VARCHAR(255) DEFAULT NULL,
  loan_rate VARCHAR(255) DEFAULT NULL,
  loan_emp VARCHAR(255) DEFAULT NULL,
  loan_occ VARCHAR(255) DEFAULT NULL,
  loan_self VARCHAR(255) DEFAULT NULL,
  cmte_id VARCHAR(255) DEFAULT NULL,
  tres_naml VARCHAR(255) DEFAULT NULL,
  tres_namf VARCHAR(255) DEFAULT NULL,
  tres_namt VARCHAR(255) DEFAULT NULL,
  tres_nams VARCHAR(255) DEFAULT NULL,
  tres_city VARCHAR(255) DEFAULT NULL,
  tres_st VARCHAR(255) DEFAULT NULL,
  tres_zip4 VARCHAR(255) DEFAULT NULL,
  intr_naml VARCHAR(255) DEFAULT NULL,
  intr_namf VARCHAR(255) DEFAULT NULL,
  intr_namt VARCHAR(255) DEFAULT NULL,
  intr_nams VARCHAR(255) DEFAULT NULL,
  intr_city VARCHAR(255) DEFAULT NULL,
  intr_st VARCHAR(255) DEFAULT NULL,
  intr_zip4 VARCHAR(255) DEFAULT NULL,
  memo_code VARCHAR(255) DEFAULT NULL,
  memo_refno VARCHAR(255) DEFAULT NULL,
  bakref_tid VARCHAR(255) DEFAULT NULL,
  xref_schnm VARCHAR(255) DEFAULT NULL,
  xref_match VARCHAR(255) DEFAULT NULL,
  loan_amt5 VARCHAR(255) DEFAULT NULL,
  loan_amt6 VARCHAR(255) DEFAULT NULL,
  loan_amt7 VARCHAR(255) DEFAULT NULL,
  loan_amt8 VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (filing_id(10),amend_id(10),line_item(10),rec_type(10),form_type(10)),
  KEY filing_id (filing_id(10)),
  KEY amend_id (amend_id(10)),
  KEY form_type (form_type(10))
);

DROP TABLE IF EXISTS ftp_lobby_amendments;
CREATE TABLE ftp_lobby_amendments (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  exec_date VARCHAR(255) DEFAULT NULL,
  from_date VARCHAR(255) DEFAULT NULL,
  thru_date VARCHAR(255) DEFAULT NULL,
  add_l_cb VARCHAR(255) DEFAULT NULL,
  add_l_eff VARCHAR(255) DEFAULT NULL,
  a_l_naml VARCHAR(255) DEFAULT NULL,
  a_l_namf VARCHAR(255) DEFAULT NULL,
  a_l_namt VARCHAR(255) DEFAULT NULL,
  a_l_nams VARCHAR(255) DEFAULT NULL,
  del_l_cb VARCHAR(255) DEFAULT NULL,
  del_l_eff VARCHAR(255) DEFAULT NULL,
  d_l_naml VARCHAR(255) DEFAULT NULL,
  d_l_namf VARCHAR(255) DEFAULT NULL,
  d_l_namt VARCHAR(255) DEFAULT NULL,
  d_l_nams VARCHAR(255) DEFAULT NULL,
  add_le_cb VARCHAR(255) DEFAULT NULL,
  add_le_eff VARCHAR(255) DEFAULT NULL,
  a_le_naml VARCHAR(255) DEFAULT NULL,
  a_le_namf VARCHAR(255) DEFAULT NULL,
  a_le_namt VARCHAR(255) DEFAULT NULL,
  a_le_nams VARCHAR(255) DEFAULT NULL,
  del_le_cb VARCHAR(255) DEFAULT NULL,
  del_le_eff VARCHAR(255) DEFAULT NULL,
  d_le_naml VARCHAR(255) DEFAULT NULL,
  d_le_namf VARCHAR(255) DEFAULT NULL,
  d_le_namt VARCHAR(255) DEFAULT NULL,
  d_le_nams VARCHAR(255) DEFAULT NULL,
  add_lf_cb VARCHAR(255) DEFAULT NULL,
  add_lf_eff VARCHAR(255) DEFAULT NULL,
  a_lf_name VARCHAR(255) DEFAULT NULL,
  del_lf_cb VARCHAR(255) DEFAULT NULL,
  del_lf_eff VARCHAR(255) DEFAULT NULL,
  d_lf_name VARCHAR(255) DEFAULT NULL,
  other_cb VARCHAR(255) DEFAULT NULL,
  other_eff VARCHAR(255) DEFAULT NULL,
  other_desc VARCHAR(255) DEFAULT NULL,
  f606_yes VARCHAR(255) DEFAULT NULL,
  f606_no VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_lobbying_chg_log;
CREATE TABLE ftp_lobbying_chg_log (
  filer_id VARCHAR(255) DEFAULT NULL,
  change_no VARCHAR(255) DEFAULT NULL,
  session_id VARCHAR(255) DEFAULT NULL,
  log_dt VARCHAR(255) DEFAULT NULL,
  filer_type VARCHAR(255) DEFAULT NULL,
  correction_flg VARCHAR(255) DEFAULT NULL,
  action VARCHAR(255) DEFAULT NULL,
  attribute_changed VARCHAR(255) DEFAULT NULL,
  ethics_dt VARCHAR(255) DEFAULT NULL,
  interests VARCHAR(255) DEFAULT NULL,
  filer_full_name VARCHAR(380) DEFAULT NULL,
  filer_city VARCHAR(255) DEFAULT NULL,
  filer_st VARCHAR(255) DEFAULT NULL,
  filer_zip VARCHAR(255) DEFAULT NULL,
  filer_phone VARCHAR(255) DEFAULT NULL,
  entity_type VARCHAR(255) DEFAULT NULL,
  entity_name VARCHAR(380) DEFAULT NULL,
  entity_city VARCHAR(255) DEFAULT NULL,
  entity_st VARCHAR(255) DEFAULT NULL,
  entity_zip VARCHAR(255) DEFAULT NULL,
  entity_phone VARCHAR(255) DEFAULT NULL,
  entity_id VARCHAR(255) DEFAULT NULL,
  responsible_officer VARCHAR(380) DEFAULT NULL,
  effect_dt VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_lobbyist_contributions1;
CREATE TABLE ftp_lobbyist_contributions1 (
  filer_id VARCHAR(255) DEFAULT NULL,
  filing_period_start_dt VARCHAR(255) DEFAULT NULL,
  filing_period_end_dt VARCHAR(255) DEFAULT NULL,
  contribution_dt VARCHAR(255) DEFAULT NULL,
  recipient_name VARCHAR(300) DEFAULT NULL,
  recipient_id VARCHAR(255) DEFAULT NULL,
  amount VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_lobbyist_contributions2;
CREATE TABLE ftp_lobbyist_contributions2 (
  filer_id VARCHAR(255) DEFAULT NULL,
  filing_period_start_dt VARCHAR(255) DEFAULT NULL,
  filing_period_end_dt VARCHAR(255) DEFAULT NULL,
  contribution_dt VARCHAR(255) DEFAULT NULL,
  recipient_name VARCHAR(300) DEFAULT NULL,
  recipient_id VARCHAR(255) DEFAULT NULL,
  amount VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_lobbyist_contributions3;
CREATE TABLE ftp_lobbyist_contributions3 (
  filer_id VARCHAR(255) DEFAULT NULL,
  filing_period_start_dt VARCHAR(255) DEFAULT NULL,
  filing_period_end_dt VARCHAR(255) DEFAULT NULL,
  contribution_dt VARCHAR(255) DEFAULT NULL,
  recipient_name VARCHAR(300) DEFAULT NULL,
  recipient_id VARCHAR(255) DEFAULT NULL,
  amount VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_lobbyist_emp_lobbyist1;
CREATE TABLE ftp_lobbyist_emp_lobbyist1 (
  lobbyist_id VARCHAR(255) DEFAULT NULL,
  employer_id VARCHAR(255) DEFAULT NULL,
  lobbyist_last_name VARCHAR(400) DEFAULT NULL,
  lobbyist_first_name VARCHAR(400) DEFAULT NULL,
  employer_name VARCHAR(400) DEFAULT NULL,
  session_id VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_lobbyist_emp_lobbyist2;
CREATE TABLE ftp_lobbyist_emp_lobbyist2 (
  lobbyist_id VARCHAR(255) DEFAULT NULL,
  employer_id VARCHAR(255) DEFAULT NULL,
  lobbyist_last_name VARCHAR(400) DEFAULT NULL,
  lobbyist_first_name VARCHAR(400) DEFAULT NULL,
  employer_name VARCHAR(400) DEFAULT NULL,
  session_id VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_lobbyist_employer1;
CREATE TABLE ftp_lobbyist_employer1 (
  employer_id VARCHAR(255) DEFAULT NULL,
  session_id VARCHAR(255) DEFAULT NULL,
  employer_name VARCHAR(300) DEFAULT NULL,
  current_qtr_amt VARCHAR(255) DEFAULT NULL,
  session_total_amt VARCHAR(255) DEFAULT NULL,
  contributor_id VARCHAR(255) DEFAULT NULL,
  interest_cd VARCHAR(255) DEFAULT NULL,
  interest_name VARCHAR(300) DEFAULT NULL,
  session_yr_1 VARCHAR(255) DEFAULT NULL,
  session_yr_2 VARCHAR(255) DEFAULT NULL,
  yr_1_ytd_amt VARCHAR(255) DEFAULT NULL,
  yr_2_ytd_amt VARCHAR(255) DEFAULT NULL,
  qtr_1 VARCHAR(255) DEFAULT NULL,
  qtr_2 VARCHAR(255) DEFAULT NULL,
  qtr_3 VARCHAR(255) DEFAULT NULL,
  qtr_4 VARCHAR(255) DEFAULT NULL,
  qtr_5 VARCHAR(255) DEFAULT NULL,
  qtr_6 VARCHAR(255) DEFAULT NULL,
  qtr_7 VARCHAR(255) DEFAULT NULL,
  qtr_8 VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_lobbyist_employer2;
CREATE TABLE ftp_lobbyist_employer2 (
  employer_id VARCHAR(255) DEFAULT NULL,
  session_id VARCHAR(255) DEFAULT NULL,
  employer_name VARCHAR(300) DEFAULT NULL,
  current_qtr_amt VARCHAR(255) DEFAULT NULL,
  session_total_amt VARCHAR(255) DEFAULT NULL,
  contributor_id VARCHAR(255) DEFAULT NULL,
  interest_cd VARCHAR(255) DEFAULT NULL,
  interest_name VARCHAR(300) DEFAULT NULL,
  session_yr_1 VARCHAR(255) DEFAULT NULL,
  session_yr_2 VARCHAR(255) DEFAULT NULL,
  yr_1_ytd_amt VARCHAR(255) DEFAULT NULL,
  yr_2_ytd_amt VARCHAR(255) DEFAULT NULL,
  qtr_1 VARCHAR(255) DEFAULT NULL,
  qtr_2 VARCHAR(255) DEFAULT NULL,
  qtr_3 VARCHAR(255) DEFAULT NULL,
  qtr_4 VARCHAR(255) DEFAULT NULL,
  qtr_5 VARCHAR(255) DEFAULT NULL,
  qtr_6 VARCHAR(255) DEFAULT NULL,
  qtr_7 VARCHAR(255) DEFAULT NULL,
  qtr_8 VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_lobbyist_employer3;
CREATE TABLE ftp_lobbyist_employer3 (
  employer_id VARCHAR(255) DEFAULT NULL,
  session_id VARCHAR(255) DEFAULT NULL,
  employer_name VARCHAR(300) DEFAULT NULL,
  current_qtr_amt VARCHAR(255) DEFAULT NULL,
  session_total_amt VARCHAR(255) DEFAULT NULL,
  contributor_id VARCHAR(255) DEFAULT NULL,
  interest_cd VARCHAR(255) DEFAULT NULL,
  interest_name VARCHAR(300) DEFAULT NULL,
  session_yr_1 VARCHAR(255) DEFAULT NULL,
  session_yr_2 VARCHAR(255) DEFAULT NULL,
  yr_1_ytd_amt VARCHAR(255) DEFAULT NULL,
  yr_2_ytd_amt VARCHAR(255) DEFAULT NULL,
  qtr_1 VARCHAR(255) DEFAULT NULL,
  qtr_2 VARCHAR(255) DEFAULT NULL,
  qtr_3 VARCHAR(255) DEFAULT NULL,
  qtr_4 VARCHAR(255) DEFAULT NULL,
  qtr_5 VARCHAR(255) DEFAULT NULL,
  qtr_6 VARCHAR(255) DEFAULT NULL,
  qtr_7 VARCHAR(255) DEFAULT NULL,
  qtr_8 VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_lobbyist_employer_firms1;
CREATE TABLE ftp_lobbyist_employer_firms1 (
  employer_id VARCHAR(255) DEFAULT NULL,
  firm_id VARCHAR(255) DEFAULT NULL,
  firm_name VARCHAR(400) DEFAULT NULL,
  session_id VARCHAR(255) DEFAULT NULL,
  termination_dt VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_lobbyist_employer_firms2;
CREATE TABLE ftp_lobbyist_employer_firms2 (
  employer_id VARCHAR(255) DEFAULT NULL,
  firm_id VARCHAR(255) DEFAULT NULL,
  firm_name VARCHAR(400) DEFAULT NULL,
  session_id VARCHAR(255) DEFAULT NULL,
  termination_dt VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_lobbyist_firm1;
CREATE TABLE ftp_lobbyist_firm1 (
  firm_id VARCHAR(255) DEFAULT NULL,
  session_id VARCHAR(255) DEFAULT NULL,
  firm_name VARCHAR(300) DEFAULT NULL,
  current_qtr_amt VARCHAR(255) DEFAULT NULL,
  session_total_amt VARCHAR(255) DEFAULT NULL,
  contributor_id VARCHAR(255) DEFAULT NULL,
  session_yr_1 VARCHAR(255) DEFAULT NULL,
  session_yr_2 VARCHAR(255) DEFAULT NULL,
  yr_1_ytd_amt VARCHAR(255) DEFAULT NULL,
  yr_2_ytd_amt VARCHAR(255) DEFAULT NULL,
  qtr_1 VARCHAR(255) DEFAULT NULL,
  qtr_2 VARCHAR(255) DEFAULT NULL,
  qtr_3 VARCHAR(255) DEFAULT NULL,
  qtr_4 VARCHAR(255) DEFAULT NULL,
  qtr_5 VARCHAR(255) DEFAULT NULL,
  qtr_6 VARCHAR(255) DEFAULT NULL,
  qtr_7 VARCHAR(255) DEFAULT NULL,
  qtr_8 VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_lobbyist_firm2;
CREATE TABLE ftp_lobbyist_firm2 (
  firm_id VARCHAR(255) DEFAULT NULL,
  session_id VARCHAR(255) DEFAULT NULL,
  firm_name VARCHAR(300) DEFAULT NULL,
  current_qtr_amt VARCHAR(255) DEFAULT NULL,
  session_total_amt VARCHAR(255) DEFAULT NULL,
  contributor_id VARCHAR(255) DEFAULT NULL,
  session_yr_1 VARCHAR(255) DEFAULT NULL,
  session_yr_2 VARCHAR(255) DEFAULT NULL,
  yr_1_ytd_amt VARCHAR(255) DEFAULT NULL,
  yr_2_ytd_amt VARCHAR(255) DEFAULT NULL,
  qtr_1 VARCHAR(255) DEFAULT NULL,
  qtr_2 VARCHAR(255) DEFAULT NULL,
  qtr_3 VARCHAR(255) DEFAULT NULL,
  qtr_4 VARCHAR(255) DEFAULT NULL,
  qtr_5 VARCHAR(255) DEFAULT NULL,
  qtr_6 VARCHAR(255) DEFAULT NULL,
  qtr_7 VARCHAR(255) DEFAULT NULL,
  qtr_8 VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_lobbyist_firm3;
CREATE TABLE ftp_lobbyist_firm3 (
  firm_id VARCHAR(255) DEFAULT NULL,
  session_id VARCHAR(255) DEFAULT NULL,
  firm_name VARCHAR(300) DEFAULT NULL,
  current_qtr_amt VARCHAR(255) DEFAULT NULL,
  session_total_amt VARCHAR(255) DEFAULT NULL,
  contributor_id VARCHAR(255) DEFAULT NULL,
  session_yr_1 VARCHAR(255) DEFAULT NULL,
  session_yr_2 VARCHAR(255) DEFAULT NULL,
  yr_1_ytd_amt VARCHAR(255) DEFAULT NULL,
  yr_2_ytd_amt VARCHAR(255) DEFAULT NULL,
  qtr_1 VARCHAR(255) DEFAULT NULL,
  qtr_2 VARCHAR(255) DEFAULT NULL,
  qtr_3 VARCHAR(255) DEFAULT NULL,
  qtr_4 VARCHAR(255) DEFAULT NULL,
  qtr_5 VARCHAR(255) DEFAULT NULL,
  qtr_6 VARCHAR(255) DEFAULT NULL,
  qtr_7 VARCHAR(255) DEFAULT NULL,
  qtr_8 VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_lobbyist_firm_employer1;
CREATE TABLE ftp_lobbyist_firm_employer1 (
  firm_id VARCHAR(255) DEFAULT NULL,
  filing_id VARCHAR(255) DEFAULT NULL,
  filing_sequence VARCHAR(255) DEFAULT NULL,
  firm_name VARCHAR(400) DEFAULT NULL,
  employer_name VARCHAR(255) DEFAULT NULL,
  rpt_start VARCHAR(255) DEFAULT NULL,
  rpt_end VARCHAR(255) DEFAULT NULL,
  per_total VARCHAR(255) DEFAULT NULL,
  cum_total VARCHAR(255) DEFAULT NULL,
  lby_actvty VARCHAR(255) DEFAULT NULL,
  ext_lby_actvty VARCHAR(4000) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_lobbyist_firm_employer2;
CREATE TABLE ftp_lobbyist_firm_employer2 (
  firm_id VARCHAR(255) DEFAULT NULL,
  filing_id VARCHAR(255) DEFAULT NULL,
  filing_sequence VARCHAR(255) DEFAULT NULL,
  firm_name VARCHAR(400) DEFAULT NULL,
  employer_name VARCHAR(255) DEFAULT NULL,
  rpt_start VARCHAR(255) DEFAULT NULL,
  rpt_end VARCHAR(255) DEFAULT NULL,
  per_total VARCHAR(255) DEFAULT NULL,
  cum_total VARCHAR(255) DEFAULT NULL,
  lby_actvty VARCHAR(255) DEFAULT NULL,
  ext_lby_actvty VARCHAR(4000) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_lobbyist_firm_lobbyist1;
CREATE TABLE ftp_lobbyist_firm_lobbyist1 (
  lobbyist_id VARCHAR(255) DEFAULT NULL,
  firm_id VARCHAR(255) DEFAULT NULL,
  lobbyist_last_name VARCHAR(400) DEFAULT NULL,
  lobbyist_first_name VARCHAR(400) DEFAULT NULL,
  firm_name VARCHAR(400) DEFAULT NULL,
  session_id VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_lobbyist_firm_lobbyist2;
CREATE TABLE ftp_lobbyist_firm_lobbyist2 (
  lobbyist_id VARCHAR(255) DEFAULT NULL,
  firm_id VARCHAR(255) DEFAULT NULL,
  lobbyist_last_name VARCHAR(400) DEFAULT NULL,
  lobbyist_first_name VARCHAR(400) DEFAULT NULL,
  firm_name VARCHAR(400) DEFAULT NULL,
  session_id VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_lookup_codes;
CREATE TABLE ftp_lookup_codes (
  code_type VARCHAR(255) DEFAULT NULL,
  code_id VARCHAR(255) DEFAULT NULL,
  code_desc VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_loth;
CREATE TABLE ftp_loth (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  line_item VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  tran_id VARCHAR(255) DEFAULT NULL,
  firm_name VARCHAR(255) DEFAULT NULL,
  firm_city VARCHAR(255) DEFAULT NULL,
  firm_st VARCHAR(255) DEFAULT NULL,
  firm_zip4 VARCHAR(255) DEFAULT NULL,
  firm_phon VARCHAR(255) DEFAULT NULL,
  subj_naml VARCHAR(255) DEFAULT NULL,
  subj_namf VARCHAR(255) DEFAULT NULL,
  subj_namt VARCHAR(255) DEFAULT NULL,
  subj_nams VARCHAR(255) DEFAULT NULL,
  pmt_date VARCHAR(255) DEFAULT NULL,
  amount VARCHAR(255) DEFAULT NULL,
  cum_amt VARCHAR(255) DEFAULT NULL,
  memo_code VARCHAR(255) DEFAULT NULL,
  memo_refno VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_lpay;
CREATE TABLE ftp_lpay (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  line_item VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  tran_id VARCHAR(255) DEFAULT NULL,
  entity_cd VARCHAR(255) DEFAULT NULL,
  emplr_naml VARCHAR(255) DEFAULT NULL,
  emplr_namf VARCHAR(255) DEFAULT NULL,
  emplr_namt VARCHAR(255) DEFAULT NULL,
  emplr_nams VARCHAR(255) DEFAULT NULL,
  emplr_city VARCHAR(255) DEFAULT NULL,
  emplr_st VARCHAR(255) DEFAULT NULL,
  emplr_zip4 VARCHAR(255) DEFAULT NULL,
  emplr_phon VARCHAR(255) DEFAULT NULL,
  lby_actvty VARCHAR(255) DEFAULT NULL,
  fees_amt VARCHAR(255) DEFAULT NULL,
  reimb_amt VARCHAR(255) DEFAULT NULL,
  advan_amt VARCHAR(255) DEFAULT NULL,
  advan_dscr VARCHAR(255) DEFAULT NULL,
  per_total VARCHAR(255) DEFAULT NULL,
  cum_total VARCHAR(255) DEFAULT NULL,
  memo_code VARCHAR(255) DEFAULT NULL,
  memo_refno VARCHAR(255) DEFAULT NULL,
  bakref_tid VARCHAR(255) DEFAULT NULL,
  emplr_id VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_names;
CREATE TABLE ftp_names (
  namid VARCHAR(255) DEFAULT NULL,
  naml VARCHAR(255) DEFAULT NULL,
  namf VARCHAR(255) DEFAULT NULL,
  namt VARCHAR(255) DEFAULT NULL,
  nams VARCHAR(255) DEFAULT NULL,
  moniker VARCHAR(255) DEFAULT NULL,
  moniker_pos VARCHAR(255) DEFAULT NULL,
  namm VARCHAR(255) DEFAULT NULL,
  fullname VARCHAR(255) DEFAULT NULL,
  naml_search VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_rcpt;
CREATE TABLE ftp_rcpt (
  filing_id VARCHAR(255) NOT NULL DEFAULT '',
  amend_id VARCHAR(255) NOT NULL DEFAULT '',
  line_item VARCHAR(255) NOT NULL DEFAULT '',
  rec_type VARCHAR(255) NOT NULL DEFAULT '',
  form_type VARCHAR(255) NOT NULL DEFAULT '',
  tran_id VARCHAR(255) DEFAULT NULL,
  entity_cd VARCHAR(255) DEFAULT NULL,
  ctrib_naml VARCHAR(255) DEFAULT NULL,
  ctrib_namf VARCHAR(255) DEFAULT NULL,
  ctrib_namt VARCHAR(255) DEFAULT NULL,
  ctrib_nams VARCHAR(255) DEFAULT NULL,
  ctrib_city VARCHAR(255) DEFAULT NULL,
  ctrib_st VARCHAR(255) DEFAULT NULL,
  ctrib_zip4 VARCHAR(255) DEFAULT NULL,
  ctrib_emp VARCHAR(255) DEFAULT NULL,
  ctrib_occ VARCHAR(255) DEFAULT NULL,
  ctrib_self VARCHAR(255) DEFAULT NULL,
  tran_type VARCHAR(255) DEFAULT NULL,
  rcpt_date VARCHAR(255) DEFAULT NULL,
  date_thru VARCHAR(255) DEFAULT NULL,
  amount VARCHAR(255) DEFAULT NULL,
  cum_ytd VARCHAR(255) DEFAULT NULL,
  cum_oth VARCHAR(255) DEFAULT NULL,
  ctrib_dscr VARCHAR(255) DEFAULT NULL,
  cmte_id VARCHAR(255) DEFAULT NULL,
  tres_naml VARCHAR(255) DEFAULT NULL,
  tres_namf VARCHAR(255) DEFAULT NULL,
  tres_namt VARCHAR(255) DEFAULT NULL,
  tres_nams VARCHAR(255) DEFAULT NULL,
  tres_city VARCHAR(255) DEFAULT NULL,
  tres_st VARCHAR(255) DEFAULT NULL,
  tres_zip4 VARCHAR(255) DEFAULT NULL,
  intr_naml VARCHAR(255) DEFAULT NULL,
  intr_namf VARCHAR(255) DEFAULT NULL,
  intr_namt VARCHAR(255) DEFAULT NULL,
  intr_nams VARCHAR(255) DEFAULT NULL,
  intr_city VARCHAR(255) DEFAULT NULL,
  intr_st VARCHAR(255) DEFAULT NULL,
  intr_zip4 VARCHAR(255) DEFAULT NULL,
  intr_emp VARCHAR(255) DEFAULT NULL,
  intr_occ VARCHAR(255) DEFAULT NULL,
  intr_self VARCHAR(255) DEFAULT NULL,
  cand_naml VARCHAR(255) DEFAULT NULL,
  cand_namf VARCHAR(255) DEFAULT NULL,
  cand_namt VARCHAR(255) DEFAULT NULL,
  cand_nams VARCHAR(255) DEFAULT NULL,
  office_cd VARCHAR(255) DEFAULT NULL,
  offic_dscr VARCHAR(255) DEFAULT NULL,
  juris_cd VARCHAR(255) DEFAULT NULL,
  juris_dscr VARCHAR(255) DEFAULT NULL,
  dist_no VARCHAR(255) DEFAULT NULL,
  off_s_h_cd VARCHAR(255) DEFAULT NULL,
  bal_name VARCHAR(255) DEFAULT NULL,
  bal_num VARCHAR(255) DEFAULT NULL,
  bal_juris VARCHAR(255) DEFAULT NULL,
  sup_opp_cd VARCHAR(255) DEFAULT NULL,
  memo_code VARCHAR(255) DEFAULT NULL,
  memo_refno VARCHAR(255) DEFAULT NULL,
  bakref_tid VARCHAR(255) DEFAULT NULL,
  xref_schnm VARCHAR(255) DEFAULT NULL,
  xref_match VARCHAR(255) DEFAULT NULL,
  int_rate VARCHAR(255) DEFAULT NULL,
  intr_cmteid VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (filing_id(10),amend_id(10),line_item(10),rec_type(10),form_type(10)),
  KEY filing_id (filing_id(10)),
  KEY amend_id (amend_id(10)),
  KEY form_type (form_type(10))
);

DROP TABLE IF EXISTS ftp_received_filings;
CREATE TABLE ftp_received_filings (
  filer_id VARCHAR(255) DEFAULT NULL,
  filing_file_name VARCHAR(255) DEFAULT NULL,
  received_date VARCHAR(255) DEFAULT NULL,
  filing_directory VARCHAR(255) DEFAULT NULL,
  filing_id VARCHAR(255) DEFAULT NULL,
  form_id VARCHAR(255) DEFAULT NULL,
  receive_comment VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_reports;
CREATE TABLE ftp_reports (
  rpt_id VARCHAR(255) DEFAULT NULL,
  rpt_name VARCHAR(255) DEFAULT NULL,
  rpt_desc_ VARCHAR(255) DEFAULT NULL,
  path VARCHAR(255) DEFAULT NULL,
  data_object VARCHAR(255) DEFAULT NULL,
  parms_flg_y_n VARCHAR(255) DEFAULT NULL,
  rpt_type VARCHAR(255) DEFAULT NULL,
  parm_definition VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_s401;
CREATE TABLE ftp_s401 (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  line_item VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  tran_id VARCHAR(255) DEFAULT NULL,
  agent_naml VARCHAR(255) DEFAULT NULL,
  agent_namf VARCHAR(255) DEFAULT NULL,
  agent_namt VARCHAR(255) DEFAULT NULL,
  agent_nams VARCHAR(255) DEFAULT NULL,
  payee_naml VARCHAR(255) DEFAULT NULL,
  payee_namf VARCHAR(255) DEFAULT NULL,
  payee_namt VARCHAR(255) DEFAULT NULL,
  payee_nams VARCHAR(255) DEFAULT NULL,
  payee_city VARCHAR(255) DEFAULT NULL,
  payee_st VARCHAR(255) DEFAULT NULL,
  payee_zip4 VARCHAR(255) DEFAULT NULL,
  amount VARCHAR(255) DEFAULT NULL,
  aggregate VARCHAR(255) DEFAULT NULL,
  expn_dscr VARCHAR(255) DEFAULT NULL,
  cand_naml VARCHAR(255) DEFAULT NULL,
  cand_namf VARCHAR(255) DEFAULT NULL,
  cand_namt VARCHAR(255) DEFAULT NULL,
  cand_nams VARCHAR(255) DEFAULT NULL,
  office_cd VARCHAR(255) DEFAULT NULL,
  offic_dscr VARCHAR(255) DEFAULT NULL,
  juris_cd VARCHAR(255) DEFAULT NULL,
  juris_dscr VARCHAR(255) DEFAULT NULL,
  dist_no VARCHAR(255) DEFAULT NULL,
  off_s_h_cd VARCHAR(255) DEFAULT NULL,
  bal_name VARCHAR(255) DEFAULT NULL,
  bal_num VARCHAR(255) DEFAULT NULL,
  bal_juris VARCHAR(255) DEFAULT NULL,
  sup_opp_cd VARCHAR(255) DEFAULT NULL,
  memo_code VARCHAR(255) DEFAULT NULL,
  memo_refno VARCHAR(255) DEFAULT NULL,
  bakref_tid VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_s496;
CREATE TABLE ftp_s496 (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  line_item VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  tran_id VARCHAR(255) DEFAULT NULL,
  amount VARCHAR(255) DEFAULT NULL,
  exp_date VARCHAR(255) DEFAULT NULL,
  expn_dscr VARCHAR(255) DEFAULT NULL,
  memo_code VARCHAR(255) DEFAULT NULL,
  memo_refno VARCHAR(255) DEFAULT NULL,
  date_thru VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_s497;
CREATE TABLE ftp_s497 (
  filing_id VARCHAR(255) NOT NULL DEFAULT '',
  amend_id VARCHAR(255) NOT NULL DEFAULT '',
  line_item VARCHAR(255) NOT NULL DEFAULT '',
  rec_type VARCHAR(255) NOT NULL DEFAULT '',
  form_type VARCHAR(255) NOT NULL DEFAULT '',
  tran_id VARCHAR(255) DEFAULT NULL,
  entity_cd VARCHAR(255) DEFAULT NULL,
  enty_naml VARCHAR(255) DEFAULT NULL,
  enty_namf VARCHAR(255) DEFAULT NULL,
  enty_namt VARCHAR(255) DEFAULT NULL,
  enty_nams VARCHAR(255) DEFAULT NULL,
  enty_city VARCHAR(255) DEFAULT NULL,
  enty_st VARCHAR(255) DEFAULT NULL,
  enty_zip4 VARCHAR(255) DEFAULT NULL,
  ctrib_emp VARCHAR(255) DEFAULT NULL,
  ctrib_occ VARCHAR(255) DEFAULT NULL,
  ctrib_self VARCHAR(255) DEFAULT NULL,
  elec_date VARCHAR(255) DEFAULT NULL,
  ctrib_date VARCHAR(255) DEFAULT NULL,
  date_thru VARCHAR(255) DEFAULT NULL,
  amount VARCHAR(255) DEFAULT NULL,
  cmte_id VARCHAR(255) DEFAULT NULL,
  cand_naml VARCHAR(255) DEFAULT NULL,
  cand_namf VARCHAR(255) DEFAULT NULL,
  cand_namt VARCHAR(255) DEFAULT NULL,
  cand_nams VARCHAR(255) DEFAULT NULL,
  office_cd VARCHAR(255) DEFAULT NULL,
  offic_dscr VARCHAR(255) DEFAULT NULL,
  juris_cd VARCHAR(255) DEFAULT NULL,
  juris_dscr VARCHAR(255) DEFAULT NULL,
  dist_no VARCHAR(255) DEFAULT NULL,
  off_s_h_cd VARCHAR(255) DEFAULT NULL,
  bal_name VARCHAR(255) DEFAULT NULL,
  bal_num VARCHAR(255) DEFAULT NULL,
  bal_juris VARCHAR(255) DEFAULT NULL,
  memo_code VARCHAR(255) DEFAULT NULL,
  memo_refno VARCHAR(255) DEFAULT NULL,
  bal_id VARCHAR(255) DEFAULT NULL,
  cand_id VARCHAR(255) DEFAULT NULL,
  sup_off_cd VARCHAR(255) DEFAULT NULL,
  sup_opp_cd VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (filing_id(10),amend_id(10),line_item(10),rec_type(10),form_type(10)),
  KEY filing_id (filing_id(10)),
  KEY amend_id (amend_id(10)),
  KEY form_type (form_type(10))
);

DROP TABLE IF EXISTS ftp_s498;
CREATE TABLE ftp_s498 (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  line_item VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  tran_id VARCHAR(255) DEFAULT NULL,
  entity_cd VARCHAR(255) DEFAULT NULL,
  cmte_id VARCHAR(255) DEFAULT NULL,
  payor_naml VARCHAR(255) DEFAULT NULL,
  payor_namf VARCHAR(255) DEFAULT NULL,
  payor_namt VARCHAR(255) DEFAULT NULL,
  payor_nams VARCHAR(255) DEFAULT NULL,
  payor_city VARCHAR(255) DEFAULT NULL,
  payor_st VARCHAR(255) DEFAULT NULL,
  payor_zip4 VARCHAR(255) DEFAULT NULL,
  date_rcvd VARCHAR(255) DEFAULT NULL,
  amt_rcvd VARCHAR(255) DEFAULT NULL,
  cand_naml VARCHAR(255) DEFAULT NULL,
  cand_namf VARCHAR(255) DEFAULT NULL,
  cand_namt VARCHAR(255) DEFAULT NULL,
  cand_nams VARCHAR(255) DEFAULT NULL,
  office_cd VARCHAR(255) DEFAULT NULL,
  offic_dscr VARCHAR(255) DEFAULT NULL,
  juris_cd VARCHAR(255) DEFAULT NULL,
  juris_dscr VARCHAR(255) DEFAULT NULL,
  dist_no VARCHAR(255) DEFAULT NULL,
  off_s_h_cd VARCHAR(255) DEFAULT NULL,
  bal_name VARCHAR(255) DEFAULT NULL,
  bal_num VARCHAR(255) DEFAULT NULL,
  bal_juris VARCHAR(255) DEFAULT NULL,
  sup_opp_cd VARCHAR(255) DEFAULT NULL,
  amt_attrib VARCHAR(255) DEFAULT NULL,
  memo_code VARCHAR(255) DEFAULT NULL,
  memo_refno VARCHAR(255) DEFAULT NULL,
  employer VARCHAR(255) DEFAULT NULL,
  occupation VARCHAR(255) DEFAULT NULL,
  selfemp_cb VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_smry;
CREATE TABLE ftp_smry (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  line_item VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  amount_a VARCHAR(255) DEFAULT NULL,
  amount_b VARCHAR(255) DEFAULT NULL,
  amount_c VARCHAR(255) DEFAULT NULL,
  elec_dt VARCHAR(255) DEFAULT NULL,
  KEY filing_id (filing_id(10)),
  KEY amend_id (amend_id(10)),
  KEY line_item (line_item(10)),
  KEY amount_c (amount_c(10))
);

DROP TABLE IF EXISTS ftp_splt;
CREATE TABLE ftp_splt (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  line_item VARCHAR(255) DEFAULT NULL,
  pform_type VARCHAR(255) DEFAULT NULL,
  ptran_id VARCHAR(255) DEFAULT NULL,
  elec_date VARCHAR(255) DEFAULT NULL,
  elec_amount VARCHAR(255) DEFAULT NULL,
  elec_code VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS ftp_text_memo;
CREATE TABLE ftp_text_memo (
  filing_id VARCHAR(255) DEFAULT NULL,
  amend_id VARCHAR(255) DEFAULT NULL,
  line_item VARCHAR(255) DEFAULT NULL,
  rec_type VARCHAR(255) DEFAULT NULL,
  form_type VARCHAR(255) DEFAULT NULL,
  ref_no VARCHAR(255) DEFAULT NULL,
  text4000 VARCHAR(4000) DEFAULT NULL
);

